import car1 from "../../images/thumbnails/vitz.jpg";
import car2 from "../../images/thumbnails/toyota.jpg";
import car3 from "../../images/thumbnails/rav4.jpg";
import car4 from "../../images/thumbnails/Highlander.jpg";
import car5 from "../../images/thumbnails/hiace.jpg";
import car6 from "../../images/thumbnails/pickup.jpg";
import car7 from "../../images/thumbnails/cooper.jpg";
import car8 from "../../images/thumbnails/Mercedes-Benz_C_.jpg";
import car9 from "../../images/thumbnails/ford.jpg";


export const carData = [
  { img: car1,
    title:"Economy", 
    price: "$60/Day", 
    name: "Toyota VITZ",
    seats:"4 Person Seat", 
    color: "Available in Green and White colors",
    gear: "Automatic gear system", 
    availability: "Available for self-drive renatls only",
    luggage: "Space for 1 large Luggage",
  },
  {  img: car2, 
     title: "Standard",
     price: "$60/Day",
     name: "Toyota Corolla, VM",
     seats:"5 Person Seat", 
     color: "Available in Black color",
     gear: "Manual gear system", 
     availability: "Available for car hire and self-drive",
     luggage: "Space for 3 medium Luggages",
  },
  { img : car3,
    title: "Medsize SUV",
    price: "$80/Day", 
    name: "Toyota Rav4",
    seats:"5 Person Seat", 
    color: "Available in Golden color",
    gear: "Automatic gear system", 
    availability: "Available for self-drive renatls only",
    luggage: "Space for 3 large Luggages",
  },
  { img: car4,
    title: "Fullsize SUV",
    price: "$80/Day",
    name: "Toyota HighLander",
    seats:"5 Person Seat", 
    color: "Available in Silver and White colors",
    gear: "Automatic gear system", 
    availability: "Available for self-drive renatls only",
    luggage: "Space for 2 large Luggages",
  },
  { img: car5,
    title: "Minivan",
    price: "$100/Day", 
    name: "Toyota HiAce",
    seats:"15 Person Seat", 
    color: "Available in Cream color",
    gear: "Automatic gear system", 
    availability: "Available for Car Hire only",
    luggage: "Space for 5 large Luggages",
  },
  { img: car6,
    title: "Pickup",
    price: "$100/Day", 
    name: "Toyota Pickup",
    seats:"4 Person Seat", 
    color: "Available in Red Color",
    gear: "Manual gear system", 
    availability: "Available for self-drive renatls only",
    luggage: "Space for Bags",
  },
  { img: car7,
      title: "Convertible",
      price: "$120/Day", 
      name: "Mini Cooper",
      seats:"4 Person Seat", 
      color: "Available in Blue color",
      gear: "Automatic gear system", 
      availability: "Available for self-drive renatls only",
      luggage: "Space for 2 medium Luggages",
    },
  { img: car8,
          title: "Luxury",
          price: "$140/Day", 
          name: "Mercedes-Benz C",
          seats:"5 Person Seat", 
          color: "Available in White Color",
          gear: "Automatic gear system", 
          availability: "Available for self-drive renatls only",
          luggage: "Space for 2 medium Luggages",
        },
  { img: car9,
      title: "Compact",
      price: "$140/Day", 
      name: "Ford Focus or Similar ",
      seats:"5 Person Seat", 
      color: "Available in Blue, White and Black Colors",
      gear: "Automatic gear system", 
      availability: "Available for self-drive renatls only",
      luggage: "Space for 3 medium Luggages",
    },

  
 ];
